
export const UPDATE_QUESTION = "UPDATE_QUESTION";
export const UPDATE_ID = "UPDATE_ID";
export const QUESTION = "QUESTION";
export const SET_QUESTION = "SET_QUESTION";
export const USER_RESPONSE = "USER_RESPONSE";
export const SET_USER_RESPONSE = "SET_USER_RESPONSE";

